name: Deploy App
# Controls when the workflow will run  
on: push
jobs:
  install_dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Build app
        run: npm run build
      - name: Test app
        run: npm test
      - name: echo Deploying
        run: echo "Application Deployed"
