name: Issues Event Logger
on: 
  issues:
    types: [opened, edited, closed]
jobs:
  log-on-details:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue event details
        run: echo "${{ toJson(github.event) }}"
